#!/usr/bin/bash
cd `dirname $0`
export $(cat .env | grep -v ^# | xargs) >/dev/null
mosquitto_pub -h ${MQTT_SERVER} -p ${MQTT_PORT} -u ${MQTT_USERNAME} -P ${MQTT_PASSWORD}  -t ${MQTT_BASE}${1} -m ${2} 